type-maps:
  cpp-type-map:
    int: int
    "[int[]]": vector<int>

  java-type-map:
    int: int
    "[int[]]": int[]

  argument-function-map:
    int: stringToInt
    "[int[]]": stringToIntArray

  return-function-map:
    int: intToString
    "[int[]]": intArrayToString